config/routes.rb
Rails.application.routes.draw do

  resources :reviews

  root "reviews#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/review.rb
class Review < ApplicationRecord

    geocoded_by :address
    after_validation :geocode

    validates :title, presence: true
    validates :body, length: { minimum: 10 }
    validates :score, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 10 }
    validates :restaurant, presence: true
    validates :cuisine, presence: true
    validates :price, numericality: { only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 3 }
    validates :address, presence: true
    
    def to_param
        id.to_s + "-" + title.parameterize
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

    def index
        # this is our list page for our reviews

        @price = params[:price]
        @cuisine = params[:cuisine]
        @address = params[:address]

        # start with all reviews
        @reviews = Review.all

        # filtering by price
        if @price.present?
            @reviews = @reviews.where(price: @price)
        end

        # filtering by cuisine
        if @cuisine.present?
            @reviews = @reviews.where(cuisine: @cuisine)
        end

        # search near location
        if @address.present?
            @reviews = @reviews.near(@address)
        end

        @number = rand(1..1000)

        @reviews = Review.all
        
    end


    def new

        @review = Review.new

    end

    def create

        # take info from form and add it to the DB
        @review = Review.new(form_params)

        # check if the model can be saved
        # if it can, redirect to home page
        # if it can't, show the new form with errors (_form.html.erb)
        if @review.save
            redirect_to root_path

        else 
            # show the view for new.html.erb
            render "new"

        end

    end

    def show

        # individual review page
        @review  = Review.find(params[:id])

    end

    def edit

        # find the individual review
        @review = Review.find(params[:id])

    end

    def update

        # find individual review
        @review = Review.find(params[:id])

        # update with new info from form
        if @review.update(form_params)

            # redirect to individual review page
            redirect_to review_path(@review)
        
        else 

            render "edit"
        
        end

    end

    def destroy

        # find the individual review
        @review = Review.find(params[:id])

        # destroy
        @review.destroy

        # redirect to homepage
        redirect_to root_path

    end

    def form_params

        params.require(:review). permit(:title, :restaurant, :body, :score, :ambiance, :cuisine, :price, :address)

    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for :page_title %> - Bien - Restaurant Reviews</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header>
      <h1>
        <%= link_to root_path do %>
          <%= image_tag "bien-logo.svg" %>
        <% end %>
      </h1>
      <h2>The Place for Restaurant Reviews</h2>
      <nav>
      <%= link_to "Add a review", new_review_path %>
      </nav>
    </header>

    <main>
      <%= yield %>
    </main>

    <footer>
      <p>Copyright Bien London 2022</p>
    </footer>
  </body>
</html>

app/views/reviews/_form.html.erb
<%= form_for @review, data: { turbo: false } do |f| %>

    <% if @review.errors.any? %>
        <div class="errors">
            <% @review.errors.full_messages.each do |message| %>
                <p><%= message %></p>
            <% end %>
        </div>
    <% end %>

    <p>
        <%= f.label :title %>
        <%= f.text_field :title %>
    </p>

    <p>
        <%= f.label :restaurant %>
        <%= f.text_field :restaurant %>
    </p>

    <p>
        <%= f.label :address %>
        <%= f.text_field :address %>
    </p>

    <p>
        <%= f.label :cuisine %>
        <%= f.text_field :cuisine %>
    </p>

    <p>
        <%= f.label :body %>
        <%= f.text_area :body %>
    </p>

    <p>
        <%= f.label :score %>
        <%= f.text_field :score %>
    </p>

    <p>
        <%= f.label :ambiance %>
        <%= f.text_field :ambiance %>
    </p>

    <p>
        <%= f.label :price %>
        <%= f.number_field :price %>
    </p>

    <%= f.submit "Submit review" %>

<% end %>

app/views/reviews/edit.html.erb
<h1>Edit your restaurant review</h1>

<%= render "form" %>

app/views/reviews/index.html.erb
<p>I can't wait until I have <%= @number %> reviews!</p>

<nav class="filters">
    <%= link_to "All prices", root_path %>
    <%= link_to "$", root_path(price: 1, cuisine: @cuisine, address: @address) %>
    <%= link_to "$$", root_path(price: 2, cuisine: @cuisine, address: @address) %>
    <%= link_to "$$$", root_path(price: 3, cuisine: @cuisine, address: @address) %>

    <%= link_to "Indian", root_path(cuisine: "Indian", price: @price, address: @address) %>
    <%= link_to "Mexican", root_path(cuisine: "Mexican", price: @price, address: @address) %>
    <%= link_to "American", root_path(cuisine: "American", price: @price, address: @address) %>

    <form action="/" >
        <input type="text" name="location" placeholder="Search location..." value="<%= @address %>">
        <input type="hidden" name="price" value="<%= @price %>">
        <input type="hidden" name="cuisine" value="<%= @cuisine %>">
    </form>
</nav>


<!-- Loop through reviews -->
<% @reviews.each do |review| %>
    <div class="review">
    <%= link_to review.title, review_path(review) %>
    </div>

<% end %>

app/views/reviews/new.html.erb
<% content_for :page_title, "Add a new review" %>

<h1>Add a restaurant review</h1>

<%= render "form" %>

app/views/reviews/show.html.erb
<% content_for :page_title, @review.title %>

<h1><%= @review.title %></h1>
<h2><%= @review.restaurant %></h2>
<h3><%= @review.cuisine %></h3>

<div class="score">
    <%= @review.score %> / 10
</div>

<% if @review.ambiance.present? %>
    <div class="ambiance">
        Ambiance: <%= @review.ambiance %>
    </div>
<% end %>

<div class="price">
    Price: <%= @review.price %>
</div>

<div class="body">
    <%= simple_format @review.body %>
</div>

<div class="address">
    <%= @review.address %>
</div>

<div class="actions">
    <%= link_to "Edit review", edit_review_path(@review) %>
    <%= button_to "Delete this review", review_path(@review), method: :delete, onclick: "return confirm('Are you sure?')" %>
</div>